def get_demo_cases() -> list[dict]:
    return [
        {
            "case_name": "pass_case",
            "scenario": {
                "scenario_type": "withdrawal",
                "scenario_label": "Need cash next year",
                "summary": "This scenario reserves 15% for near-term liquidity while keeping the rest invested.",
                "profiler_output": {
                    "investor_segment": "Goal-Focused Planner",
                    "risk_profile": "Balanced",
                    "liquidity_need": "high",
                    "time_horizon_bucket": "near_term",
                    "recommended_scenario_type": "withdrawal",
                    "confidence": 0.91,
                    "reasoning": "Near-term spending need and balanced risk profile route to withdrawal.",
                    "target_profile_name": "Goal-Focused Planner",
                    "allocation_targets": {
                        "Individual Stocks": 15.0,
                        "Broad Market Funds": 30.0,
                        "International Funds": 15.0,
                        "Defensive / Stability Funds": 20.0,
                        "Dividend / Income Funds": 10.0,
                        "Thematic / Sector Exposure": 0.0,
                        "Liquidity Placeholder": 10.0,
                    },
                    "max_single_holding_pct": 15.0,
                    "max_sector_pct": 25.0,
                    "rebalance_trigger_pct": 6.0,
                    "warning_rules": ["Protect near-term goals with a cash or short-duration sleeve."],
                    "target_stock_pct": 70.0,
                    "planning_style": "Simple",
                    "tags": ["goal-focused_planner"],
                    "explanation": "Goal-Focused Planner mapped to a balanced profile.",
                },
                "current_health": {"overall": 52.0, "diversification": 60.0, "concentration": 50.0, "risk_alignment": 55.0, "liquidity_readiness": 40.0, "label": "Fair"},
                "projected_health": {"overall": 63.0, "diversification": 66.0, "concentration": 60.0, "risk_alignment": 63.0, "liquidity_readiness": 62.0, "label": "Good"},
                "current_allocation": {
                    "Individual Stocks": 40.0,
                    "Broad Market Funds": 25.0,
                    "International Funds": 10.0,
                    "Defensive / Stability Funds": 10.0,
                    "Dividend / Income Funds": 5.0,
                    "Thematic / Sector Exposure": 5.0,
                    "Liquidity Placeholder": 5.0,
                },
                "proposed_allocation": {
                    "Individual Stocks": 25.0,
                    "Broad Market Funds": 30.0,
                    "International Funds": 15.0,
                    "Defensive / Stability Funds": 15.0,
                    "Dividend / Income Funds": 5.0,
                    "Thematic / Sector Exposure": 0.0,
                    "Liquidity Placeholder": 10.0,
                },
                "before_allocation": {"AAPL": 25.0, "VTI": 25.0, "VXUS": 10.0, "BND": 10.0, "SCHD": 5.0, "QQQ": 5.0, "BIL": 20.0},
                "after_allocation": {"AAPL": 15.0, "VTI": 30.0, "VXUS": 15.0, "BND": 15.0, "SCHD": 5.0, "BIL": 20.0},
                "actions": [
                    {"symbol": "AAPL", "name": "Apple Inc.", "action": "trim", "owned_holding": True, "current_weight_pct": 25.0, "target_weight_pct": 15.0, "change_pct": -10.0, "reason": "Reduce stock concentration."},
                    {"symbol": "BIL", "name": "SPDR Bloomberg 1-3 Month T-Bill ETF", "action": "add", "owned_holding": False, "current_weight_pct": 5.0, "target_weight_pct": 10.0, "change_pct": 5.0, "reason": "Increase near-term liquidity."},
                ],
                "transparency": {
                    "why_suggested": "Money needed soon should not depend on a strong stock market right before withdrawal.",
                    "what_changes": "The proposal would reduce Individual Stocks by 15.0%, then increase Defensive / Stability Funds and Liquidity Placeholder.",
                    "upside": "Improves liquidity readiness.",
                    "downside": "May lag a strong rally.",
                    "selling_impact": "Trims are partial rather than full exits.",
                    "guardrail_note": "Deterministic math only.",
                    "goal_alignment": "Protects near-term goals while keeping the rest invested.",
                },
                "market_context": {
                    "source": "syndicated_csv",
                    "supported_symbol_count": 119,
                    "top_sectors": ["Technology", "Fixed Income"],
                    "diversified_weight_pct": 60.0,
                    "narrative": "Latest available market proxy shows a more balanced post-withdrawal mix.",
                },
                "estimated_cost_note": "Costs are illustrative only and based on deterministic proxy pricing.",
                "estimated_tax_note": "Tax notes are generic educational guidance. Sales may create tax impact.",
            },
            "request_audit": {"data_sources": ["syndicated_csv"], "agents": ["scenario_agent"], "checks": [{"name": "no_live_market_api", "status": "passed", "detail": "CSV only"}]},
        },
        {
            "case_name": "review_needed_case",
            "scenario": {
                "scenario_type": "market_drop",
                "scenario_label": "Market drops 20%",
                "summary": "This scenario trims a concentrated growth position before a drawdown.",
                "profiler_output": {
                    "investor_segment": "High-Risk Watchlist User",
                    "risk_profile": "Growth",
                    "liquidity_need": "low",
                    "time_horizon_bucket": "long_term",
                    "recommended_scenario_type": "market_drop",
                    "confidence": 0.9,
                    "reasoning": "Growth profile with concentrated ideas routes to market_drop.",
                    "target_profile_name": "High-Risk Watchlist User",
                    "allocation_targets": {
                        "Individual Stocks": 40.0,
                        "Broad Market Funds": 15.0,
                        "International Funds": 10.0,
                        "Defensive / Stability Funds": 5.0,
                        "Dividend / Income Funds": 0.0,
                        "Thematic / Sector Exposure": 25.0,
                        "Liquidity Placeholder": 5.0,
                    },
                    "max_single_holding_pct": 16.0,
                    "max_sector_pct": 28.0,
                    "rebalance_trigger_pct": 10.0,
                    "warning_rules": [],
                    "target_stock_pct": 90.0,
                    "planning_style": "Simple",
                    "tags": ["high-risk_watchlist_user"],
                    "explanation": "High-risk watchlist profile.",
                },
                "current_health": {"overall": 40.0, "diversification": 25.0, "concentration": 20.0, "risk_alignment": 65.0, "liquidity_readiness": 35.0, "label": "Needs Attention"},
                "projected_health": {"overall": 44.0, "diversification": 30.0, "concentration": 25.0, "risk_alignment": 66.0, "liquidity_readiness": 35.0, "label": "Needs Attention"},
                "current_allocation": {
                    "Individual Stocks": 45.0,
                    "Broad Market Funds": 10.0,
                    "International Funds": 10.0,
                    "Defensive / Stability Funds": 5.0,
                    "Dividend / Income Funds": 0.0,
                    "Thematic / Sector Exposure": 25.0,
                    "Liquidity Placeholder": 5.0,
                },
                "proposed_allocation": {
                    "Individual Stocks": 42.0,
                    "Broad Market Funds": 13.0,
                    "International Funds": 10.0,
                    "Defensive / Stability Funds": 5.0,
                    "Dividend / Income Funds": 0.0,
                    "Thematic / Sector Exposure": 25.0,
                    "Liquidity Placeholder": 5.0,
                },
                "before_allocation": {"TSLA": 35.0, "QQQ": 25.0, "VTI": 10.0, "VXUS": 10.0, "BIL": 5.0, "SMH": 15.0},
                "after_allocation": {"TSLA": 30.0, "QQQ": 25.0, "VTI": 13.0, "VXUS": 10.0, "BIL": 5.0, "SMH": 17.0},
                "actions": [
                    {"symbol": "TSLA", "name": "Tesla Inc.", "action": "trim", "owned_holding": True, "current_weight_pct": 35.0, "target_weight_pct": 30.0, "change_pct": -5.0, "reason": "Reduce single-name concentration."},
                    {"symbol": "VTI", "name": "Vanguard Total Stock Market ETF", "action": "add", "owned_holding": False, "current_weight_pct": 10.0, "target_weight_pct": 13.0, "change_pct": 3.0, "reason": "Add broader market exposure."},
                ],
                "transparency": {
                    "why_suggested": "A drawdown stress test checks concentration.",
                    "what_changes": "Trim a winner modestly and add broader exposure.",
                    "upside": "Slightly lower downside concentration.",
                    "downside": "Could lag if the winner keeps running.",
                    "selling_impact": "Partial trims only.",
                    "guardrail_note": "Deterministic math only.",
                    "goal_alignment": "",
                },
                "market_context": {
                    "source": "syndicated_csv",
                    "supported_symbol_count": 119,
                    "top_sectors": ["Technology"],
                    "diversified_weight_pct": 25.0,
                    "narrative": "Technology remains dominant.",
                },
                "estimated_cost_note": "Estimated using market proxy prices.",
                "estimated_tax_note": "Generic tax note applies to any sale.",
            },
            "request_audit": {"data_sources": ["syndicated_csv"], "agents": ["scenario_agent"], "checks": [{"name": "no_live_market_api", "status": "passed", "detail": "CSV only"}]},
        },
        {
            "case_name": "fail_case",
            "scenario": {
                "scenario_type": "concentration",
                "scenario_label": "One holding is too big",
                "summary": "This guaranteed plan will definitely improve returns by trimming the largest name.",
                "profiler_output": {
                    "investor_segment": "Balanced Builder",
                    "risk_profile": "Balanced",
                    "liquidity_need": "low",
                    "time_horizon_bucket": "long_term",
                    "recommended_scenario_type": "concentration",
                    "confidence": 0.85,
                    "reasoning": "Concentration concern routes to concentration scenario.",
                    "target_profile_name": "",
                    "allocation_targets": {},
                    "max_single_holding_pct": 18.0,
                    "max_sector_pct": 28.0,
                    "rebalance_trigger_pct": 7.0,
                    "warning_rules": [],
                    "target_stock_pct": 80.0,
                    "planning_style": "Simple",
                    "tags": ["balanced_builder"],
                    "explanation": "Balanced profile.",
                },
                "current_health": {"overall": 35.0, "diversification": 20.0, "concentration": 15.0, "risk_alignment": 60.0, "liquidity_readiness": 35.0, "label": "Needs Attention"},
                "projected_health": {"overall": 36.0, "diversification": 21.0, "concentration": 16.0, "risk_alignment": 61.0, "liquidity_readiness": 35.0, "label": "Needs Attention"},
                "current_allocation": {
                    "Individual Stocks": 70.0,
                    "Broad Market Funds": 20.0,
                    "International Funds": 10.0,
                    "Defensive / Stability Funds": 0.0,
                    "Dividend / Income Funds": 0.0,
                    "Thematic / Sector Exposure": 0.0,
                    "Liquidity Placeholder": 0.0,
                },
                "proposed_allocation": {
                    "Individual Stocks": 80.0,
                    "Broad Market Funds": 25.0,
                    "International Funds": 10.0,
                    "Defensive / Stability Funds": 10.0,
                    "Dividend / Income Funds": 0.0,
                    "Thematic / Sector Exposure": 0.0,
                    "Liquidity Placeholder": -5.0,
                },
                "before_allocation": {"AAPL": 60.0, "VTI": 20.0, "VXUS": 10.0, "BND": 10.0},
                "after_allocation": {"AAPL": 65.0, "VTI": 25.0, "VXUS": 10.0},
                "actions": [
                    {"symbol": "AAPL", "name": "Apple Inc.", "action": "trim", "owned_holding": True, "current_weight_pct": 60.0, "target_weight_pct": 55.0, "change_pct": -5.0, "reason": "Trim oversized holding."}
                ],
                "transparency": {
                    "why_suggested": "",
                    "what_changes": "",
                    "upside": "Guaranteed upside.",
                    "downside": "",
                    "selling_impact": "Sell now.",
                    "guardrail_note": "",
                    "goal_alignment": "",
                },
                "market_context": {
                    "source": "unknown",
                    "supported_symbol_count": 0,
                    "top_sectors": [],
                    "diversified_weight_pct": 0.0,
                    "narrative": "",
                },
                "estimated_cost_note": "",
                "estimated_tax_note": "",
            },
            "request_audit": {"data_sources": [], "agents": [], "checks": []},
        },
    ]
